version: "3"
services:
  issnotifierbot:
    container_name: issnotifierbot
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./persistent_data:/app/persistent_data # Map the host directory to the container
    environment:
      - TELEGRAM_API_KEY=<your telegram api key>
